name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install dependency
        run: npm install
        working-directory: ./MovieAPI

      - name: Build
        run: npm run dev